### ISSUE TITLE
TODO: propose syntax for $merge, $mergeDeep, $flatten, $flattenDeep, $concat/$join

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#10]
I'm thinking `{$merge: [{a: 1, b: 1}, {b: 2}]} = {a: 1, b: 2}`, ie. right side overwrites.
$mergeDeep is the same except it does it recursively to all objects.

`{$flatten: [[1,2], [3,4], [5]]} = [1,2,3,4,5]` 

Maybe we don't need $concat/$join once we have $flatten, or the other way around... Something to think about.

**Comment by hammad13060** [comment]
Yes these constructs look like a great idea. Probably we can add more lodash features in future.

**Comment by jonasfj** [comment]
Yeah, who knows, `$pick`, `$omit`, `$pairs` could also be useful... but we can probably do without those for a long time. Notably I want to extend objects and to extend lists, merge/flatten will let us to do that.

**Comment by TheNavigat** [comment]
`{$flatten: [[1,2], [3,4], [5]]} = [1,2,3,4]`

Shouldn't the result be `[1,2,3,4,5]`?

**Comment by djmitche** [comment]
I'm curious why these are operators instead of built-ins.. wouldn't `{$eval: 'flatten([..])`}` be more flexible?

**Comment by djmitche** [comment]
And, yes, `,5` is correct - edited to fix.

**Comment by jonasfj** [comment]
> I'm curious why these are operators instead of built-ins.. wouldn't {$eval: 'flatten([..])}` be more flexible?

Using `$let` that is now possible...  but it's not as elegant...

Example:
```yaml
$flatten:
 - a
 - [b, c]
 - $if: 'value == 3'
    then:
      - [d, e]
```
becomes `[a,b,c]` or `[a,b,c,d,e]` depending on `value`.

Imagine this with `$let` and `$eval`, it's not as pretty

**Comment by djmitche** [comment]
Makes sense, thanks

**Comment by TheNavigat** [comment]
How should `$mergeDeep` act like?

If we have `{$mergeDeep: [{a: 1, b: 2}, {a: {b: 1}, b: {a: 3}, c: {d: {e: 5}}}]}, what should be the result?

**Comment by djmitche** [comment]
I'm tempted to say let's leave the "deep" variants out for now.  We have a pretty sophisticated language already!  Better to get on to the Python implementation, and we can revisit these operators if we find a need for them.

**Comment by djmitche** [comment]
I think these have all been implemented, with the exception of `$concat`.  I think we have a complex-enough language already, so let's leave it there :)

**Comment by jonasfj** [comment]
With $flatten do we even need $concat?

Den 13. jun. 2017 11.30 AM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by djmitche** [comment]
Probably not!
