### ISSUE TITLE
question: rename $dumps -> $json

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#11]
I just realized that `dumps` might only be obvious to python users. And even then they only know it as `json.dumps`.

Should we consider renaming the construct `{$json: ...}` or `{$stringify: ...}`, any other ideas?

**Comment by hammad13060** [comment]
How about ```$toString```, although I also like ```$stringify```.

**Comment by jonasfj** [comment]
Hmm, $toString might also work.. although a string does become double
wrapped...
IE `{$toString: 'test'} = '"test"'` which is unexpected for a toString on a
string...

Note: the idea is that the result string can be parsed as JSON... It's
currently called dumps because it allows you to dump an object structure
into a string... For example dumping an object structure into and
environment variable for a task...

Den 22. jan. 2017 12.16 PM skrev "Hammad Akhtar" <notifications@github.com>:

**Comment by hammad13060** [comment]
From what I understand about ```$dumps``` it simply evaluates an expression, convert it to a string and assign it to the appropriate key. It is evident [here](https://github.com/taskcluster/json-e/blob/master/specification.yml#L43) and [here](https://github.com/taskcluster/json-e/blob/master/specification.yml#L255).

**Comment by hammad13060** [comment]
No double wrapping of string takes place.

**Comment by hammad13060** [comment]
Probably we will be able to prevent such double wrapping in code.

**Comment by jonasfj** [comment]
I see double wrapping as intended behavior... I know storing a JSON string inside a property in JSON is bad... Example:
```js
{
   "env": {
    "HOME": "/home/worker/",
    "DATA": "[1,2,3,\"test\",{\"key\": 34}]",
    "DATA2": "\"my string\""
  }
}
```
In this case both `DATA` and `DATA2` can be fed to `JSON.parse()` and they will return a JSON value.

---
Note: in `{$dumps: ...}` the `...` is a json-e expression, **not** an expression from our embedded expression based language.

**Comment by jonasfj** [comment]
Yes, JSON strings inside strings in another JSON object as above isn't pretty. But sometimes it's useful.. For example if `DATA` defines an environment variable...

**Comment by djmitche** [comment]
+1 for `{$json: ..}`.

The double-quoting is, indeed, a feature.  It would be inconsistent for `{$json: x}` to evaluate to `abc` if x is `"abc"`, but to `{"abc": def"}` if x is an object -- one of those can be parsed as JSON, and the other cannot.

**Comment by jonasfj** [comment]
Any other changes you could imagine? I would like to lock the minimal
section as I'm planning to use it in actions.json

Den 23. jan. 2017 8.43 AM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by djmitche** [comment]
Nothing in `specification.yml` stands out to me, aside from `$dumps`
