### ISSUE TITLE
Stop checking in the generated site

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#117]
Now that we're using webpack, each generation of the site will be slightly different (I think webpack uses random IDs).

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd might help to get Travis to automatically build and export the result to the gh-pages branch.

**Comment by eliperelman** [comment]
We did this in the unified-logviewer: https://github.com/taskcluster/unified-logviewer/blob/master/deploy.sh
