### ISSUE TITLE
Play with Pratt Parsers

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#13]
I was looking for how to easily implement the same parser in multiple languages... Peg.js isn't a good fit for portability. Nor is it super simple.

For expressions we should probably look at:
http://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/

I couldn't stop myself from playing with a lever today... This might be the way to write a simple parser and ensure consistency across multiple implementations....

**Comment by hammad13060** [comment]
Just went through the post. This looks very promising.

**Comment by jonasfj** [comment]
@hammad13060, yeah, it's looks super simple.
In fact I'm surprised it haven't been raised to a higher level API.
I haven't done it yet, but I think it's possible to construct a `PrattParser` class such that a parser is defined as follows: https://gist.github.com/jonasfj/f0956e1035824c6ebe02182038f161ec

It might even be possible to reference other parsers in order to have multiple rules... Like in a real grammar...

**Comment by jonasfj** [comment]
nah, forgot the gist above, we can't make it that elegant... Not if we wish to support repeatition, for expression like lists... But I still think a pratt parser is the way to go :)

**Comment by hammad13060** [comment]
@jonasfj do you have any specific design in mind for this. I feel we should start working on the expression language.

**Comment by jonasfj** [comment]
I agree we should start working on it... I had a design, but after playing with it I found that it definitely wouldn't work. So by all means feel free to start working on it.

Ideally, we write it in such a way that it's easy to write the same code in python. I suspect we should implement it in both language, to make sure that it's possible...

**Comment by jonasfj** [comment]
@hammad13060, The only useful thing I got working was tokenizer using regular expressions:
https://gist.github.com/jonasfj/3d0e26c028f6cdcfed06c06b1f7ab9ce

By listing all tokens in an array the array index can be id of the token. Hence, we don't need to use a mapping from to rules, but can just use an array... As all tokens have an integer identifier :)

I also suspect that precedence can be expressed as:
```js
  precedence: [
    ['+', '-'],
    ['*', '/'],
  ],
```
That way we don't have to write numbers, because we can generate a mapping from token to precedence-level from the declaration above.

But I haven't found a good way to abstract rules... We might have to use parselet functions like the article does.
As anything else will likely involve DFA construction which seems a bit overkill.

**Comment by hammad13060** [comment]
Hey @jonasfj sorry for replying late

Tokeniser looks good. I think we can implement rules using parselets [this](https://gist.github.com/hammad13060/f3f4c039d9de315ac1f8bb840ac5e204) way.

**Comment by hammad13060** [comment]
Note that above is not a complete implementation but just gives an idea of how we can proceed.

**Comment by hammad13060** [comment]
Have a look at code from [this line](https://gist.github.com/hammad13060/f3f4c039d9de315ac1f8bb840ac5e204#file-parselet-support-js-L92) onwards

**Comment by jonasfj** [comment]
@hammad13060,
That looks like a step in the right direction. I cleanup the design a little:
https://gist.github.com/jonasfj/72343f42146d1b4a704612c63b3e5fb1
I'm not sure if we can infer the precendence level and wrap it into the `ctx` object, or if we need the rule writer to always specify it... Either way, this is pretty much what you outlined but with some nicer API.

From looking at it, I think we design a `PrattParser` class right, we can port it to python pretty easily... using lambda expressions instead of functions for most of it...

**Comment by jonasfj** [comment]
Forget I said we can infer precedence level, we'll have to pass it as an argument..
But we can pass a string, and then have a mapping from string to precedecene level.
In fact we don't need to specify the precedence level as int there either, if it's a list...
Example:
https://gist.github.com/jonasfj/72343f42146d1b4a704612c63b3e5fb1

Ps. This resource was helpful in understanding the pratt parsers are bit more:
http://effbot.org/zone/simple-top-down-parsing.htm

**Comment by jonasfj** [comment]
Played a bit more with the setup:
https://gist.github.com/jonasfj/389ad807923684f2bdbda788bd379de7

I think we can finish this up with better error messages, and more asserts :)
Then land it... Porting to python shouldn't be too hard.

**Comment by hammad13060** [comment]
Just went through the code it looks great. However I think we should slightly tweak the rules so that evaluation becomes easier.

```Currently rules look like this```

```javascript
prefixRules: {
    'number': (token, ctx) => ['number', token.value],
    '-':      (token, ctx) => ['-', ctx.parse('unary')],
    '+':      (token, ctx) => ['+', ctx.parse('unary')],
    'id':     (token, ctx) => ['id:', token.value],
    '[':      (token, ctx) => ['list:', ctx.parseList(',', ']')],
    '(':      (token, ctx) => {let v = ctx.parse(); ctx.require(')'); return v;},
    '{':      (token, ctx) => ['obj:', parseObject(ctx)],
  },
  infixRules: {
    '+': (left, token, ctx) => [left, '+', ctx.parse('+')],
    '-': (left, token, ctx) => [left, '-', ctx.parse('-')],
    '*': (left, token, ctx) => [left, '*', ctx.parse('*')],
    '/': (left, token, ctx) => [left, '/', ctx.parse('/')],
    '[': (left, token, ctx) => {let v = ['access:', left, ctx.parse()]; ctx.require(']'); return v;},
    '.': (left, token, ctx) => ['access:', left, ctx.require('id').value],
    '(': (left, token, ctx) => ['apply:', left, parseList(ctx, ',', ')')],
  }
```


```This is what I suggest```

```javascript
prefixRules: {
    'number': (token, ctx) => ['prefix','number', token.value],
    '-':      (token, ctx) => ['prefix','-', ctx.parse('unary')],
    '+':      (token, ctx) => ['prefix','+', ctx.parse('unary')],
    'id':     (token, ctx) => ['prefix','id:', token.value],
    '[':      (token, ctx) => ['prefix','list:', ctx.parseList(',', ']')],
    '(':      (token, ctx) => {let v = ctx.parse(); ctx.require(')'); return v;},
    '{':      (token, ctx) => ['prefix','obj:', parseObject(ctx)],
  },
  infixRules: {
    '+': (left, token, ctx) => ['infix',left, '+', ctx.parse('+')],
    '-': (left, token, ctx) => ['infix',left, '-', ctx.parse('-')],
    '*': (left, token, ctx) => ['infix',left, '*', ctx.parse('*')],
    '/': (left, token, ctx) => ['infix',left, '/', ctx.parse('/')],
    '[': (left, token, ctx) => {let v = ['infix',left, 'access:', ctx.parse()]; ctx.require(']'); return v;},
    '.': (left, token, ctx) => ['infix',left, 'access:', ctx.require('id').value],
    '(': (left, token, ctx) => ['infix',left,'apply:', parseList(ctx, ',', ')')],
  }
```


If we will specify the rules this way we can easily write a recursive evaluator which evaluates rules first by classifying object as infix or prefix and then doing necessary evaluation.

In prefix rules I have moved the 'access:' operator next to 'left' since we want to follow same convention for prefix operators i.e left, operator, right.


If you can provide me with this I can quickly jot down an evaluator.

**Comment by hammad13060** [comment]
I am assuming you will provide me with a parse tree and we can then use an evaluator like [this](https://gist.github.com/hammad13060/3330cf322fd2bf49266b223df773a3da) for evaluation. 
P.S. I have not tested this code. Consider it like pseudo code.

**Comment by jonasfj** [comment]
Hehe, very little of the code here have been tested much :)

But we don't need a parse tree... The rules I posted just created one so
that it was easy to see if it was parsing precedence correctly :)
We can change to rules to do one-fly-evaluation, see the rules that I
commented out, they pretty much do that...

If you have time I guess now is a good time to start to glue all of this
together and make it run the test cases... Then we can add more test cases
as we add more features.

If your up for it, please don't hold back... Otherwise, I might have time
to glue some of this together at end of the week... Right now I'm playing
with workers, which need more stability :)

Den 31. jan. 2017 5.53 AM skrev "Hammad Akhtar" <notifications@github.com>:

**Comment by hammad13060** [comment]
Ya sure I'll tie up the code together. I am thinking that we can maintain it as a separate library. What would you like to name it.

**Comment by jonasfj** [comment]
I think we should just keep it all in one module to get started... Also if
we want Python port it might be smart not to split it out, as that makes
compatibility hard to do...

If the Pratt parser changes under us, it's hard to do compatibility...
Besides the source isn't that big...

Den 31. jan. 2017 7.53 AM skrev "Hammad Akhtar" <notifications@github.com>:

**Comment by hammad13060** [comment]
Ya sure I can do that 👍

**Comment by hammad13060** [comment]
Hi @jonasfj 
1. I have included the pratt-parser to the json-e project [here](https://github.com/hammad13060/json-e/tree/pratt-parser/src/parser)
2. [Here](https://github.com/hammad13060/json-e/blob/pratt-parser/test/tests.js#L24) you will find some successful tests for pratt-parser
3. [Here](https://github.com/hammad13060/json-e/blob/pratt-parser/src/parser/configs.js#L94) I have added some new rules.

Let me know what do you think :)

**Comment by jonasfj** [comment]
@hammad13060, that's looks really good...
I propose filing it into this repository..
directory layout something like:
```
src/
  tokenizer.js
  prattparser.js
  interpreter.js (formerly config)
  index.js  (implements the rest of json-e)
test/
  specification_test.js  (loads YAML from specifycation and generates test cases from it, see email)
  expressions_test.js (loads expression-spec.yml, see email where I outlined idea for this)
```

Note: I propose we rename `config.js` to `interpreter.js` and have to look like:
```js
....

module.exports = new PrattParser({
  ignore: '\\s+',
  ....
});
```

Because `new PrattParser(config)` is technically an interpreter... We don't really create a abstract syntax tree :)
We evaluate the expression as we're parsing it, so it's actually an _interpreter_ already :)

-----
@hammad13060,
Also please copy/paste and file as PRs against this repo, then it's a lot easier to provide inline feedback and iterate on the code.

**Comment by hammad13060** [comment]
Will be able to do it by tomorrow. Got to go.

**Comment by djmitche** [comment]
What needs to happen here?

**Comment by jonasfj** [comment]
this is done...
