### ISSUE TITLE
Reserve `$<keyword>` for future constructs...

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#151]
Let's just require that things are always written with `{$$<whatever>: ...}` to get `{$<whatever>: ...}`.

That way we can safely introduce new $-keywords without breaking existing templates.

**Right now** the `{$$<keyword>: ...}` to `{$keyword: ...}` escaping only works for reserved keywords.

---

Notably, I could imagine a $zip, $unzip, $pairs, $unique, $reduce, {$call: ..., with: ...}, {$transform: '...', ...}, and others from lodash.. Arguably we should think of a way these constructs will be useful before we introduce them.

**Comment by djmitche** [comment]
I believe this is already the case - do you know otherwise?

**Comment by jonasfj** [comment]
Hmm, it seems to me that we only escape for keyword is reserved:
https://github.com/taskcluster/json-e/blob/b6d254291a42f09a7b4474464180ba283b998c99/src/index.js#L239-L241

If we wanted to do this `{$reservedKeyword: null}` should throw an error rather than render to `{$reservedKeyword: null}`...

The test case is thus very easy...

**Comment by jonasfj** [comment]
Note: I propose that we only reserve: `/^\$[a-zA-Z][a-zA-Z0-9]*$/ as we're only interested in reserving future keywords...

**Comment by djmitche** [comment]
Hah, I meant to do the exact opposite.  Good spot!
