### ISSUE TITLE
`$json` should handle functions with an error -`{$json: {$eval: 'min'}}`

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#158]
`{$json: {$eval: 'min'}}` is the test case, it produces some weird error that isn't handled.
I think we want to explicitly check for this...

**Comment by djmitche** [comment]
Ideally we don't have to recurse over the whole structure, but yes, we should handle this cleanly.  Isn't it acceptable to raise a JSON-e error?

**Comment by jonasfj** [comment]
Yeah, some clean error is all we want..

**Comment by viraj96** [comment]
@djmitche In the context of above test case, I presume the error originally is generated because no arguments are provided to `min`. As far as I have read the code, I see that `max` and `min` have `minArgs` defined as 1 and if `args.length` is less than `minArgs` then a `builtinError` is thown. So, now my question is what would `args.length` be in the above case because if it was a number then that `if` condition should have been triggered, right? Also, is there something that I am missing?

**Comment by jonasfj** [comment]
> In the context of above test case, I presume the error originally is generated because no arguments are provided to min.

No that's not correct.

The value of the json-e expression `{$eval: 'min'}` is a function.
Now we don't allow json-e to evaluate to functions, or well, we somewhat do...

Example of something not allowed:
```yaml
$eval: 'min'  # not a legal json-e document, but it's a legal expression within another json-e document
```

Example of something allowed:
```yaml
$let:
  x: {$eval: 'min'}
in:
  test: {$eval: 'x(4,1)'}   # this evaluates to 1
```

So it's permitted to do `{$eval: 'min'}` which is useful in cases where you have a function that returns another function... like `{$eval: make_function("hello")("jonas")}`, if `make_function` takes a string and returns a function that also accepts a string then this is perfectly sane.. It also implies that functions can be values in json-e, but we only allow them as intermediate values.

**Comment by Nicrii** [comment]
@owlishDeveloper I’d like to work on this issue

**Comment by owlishDeveloper** [comment]
@Nicrii you're very welcome to it!

**Comment by owlishDeveloper** [comment]
Fixed https://github.com/taskcluster/json-e/pull/330

**Comment by owlishDeveloper** [comment]
The above fix did not cover all the test cases, so I re-open this. The test cases that should be covered:

```
# currently would return undefined but should throw a nice error:
template: {$json: {$eval: min}}
template: {$json: {$eval: fromNow}}
template: {$json: {$eval: '[min, max]'}}
template: {$json: [{$eval: 'min'}]}
template: {$json: {maximum: {$eval: 'max'}}}
template: {$json: [{minimum: {$eval: 'min'}, {maximum: {$eval: 'max'}}]}

# should return strings containing return values of the functions
template: {$json: [min, max]}
template: {$json: {$eval: "fromNow('1 day')"}}
template: {$json: [{$eval: 'min(2, 3)'}]}
template: {$json: {minimum: {$eval: 'min(1, 2)'}}}
```
