### ISSUE TITLE
Prohibit extra keys in operations

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#176]
```
$if: 'x == 10'
then:
foo: bar
else:
  bing: baz
```

Is subtly wrong. that `foo` property in the top-level object will be ignored, with no error.

**Comment by djmitche** [comment]
So the idea here is that for an operator (`{$.., ..}`), *only* the defined properties should be allowed.  For `$merge`, for example, no other properties are allowed.  For `$if`, `then` and `else` are allowed (but not `foo`!)

**Comment by prachi1210** [comment]
I'd like to work on this issue. We want to disallow undefined properties corresponding to the following operators:
- `$if-then-else`
- `$flatten`
- `$flattenDeep`
- `$merge`
Are there any that I missed?

**Comment by djmitche** [comment]
All of the operators, please :)

**Comment by prachi1210** [comment]
Just a clarification, disallowing undefined properties would require me to flag them as errors in specifications, right?
