### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by edmorley** [taskcluster/json-e#193]
I couldn't find a CHANGES.md, or section in the README, or release notes added via the GitHub 'releases' feature.

I don't suppose some could be added for future releases?

**Comment by djmitche** [comment]
I think we will rely on the git history for that.

**Comment by djmitche** [comment]
@edmorley based on https://github.com/taskcluster/taskcluster-rfcs/issues/101and http://keepachangelog.com/en/1.0.0/ git history's probably not so good.

I know of [towncrier](https://pypi.python.org/pypi/towncrier) to help with this.  Do you have other tools?

**Comment by edmorley** [comment]
I personally haven't used towncrier, but I know pip uses it:
https://pip.pypa.io/en/latest/development/#adding-a-news-entry

**Comment by djmitche** [comment]
Per #229 @jonasfj would like a more thorough solution..

**Comment by jonasfj** [comment]
Okay, I was favoring deriving from git commit log, and just adding something to enforce a decent commit log:
https://conventionalcommits.org/

But I see the counter arguments..
