### ISSUE TITLE
`$map` on objects is weird when `each` results on an array

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#208]
```yml
$map: {hello: 5, test: 9}
each(x):
 - '${x.key}'
 - {$eval: 'x.val+1'}
```
results in:
```yml
'0': test
'1': 10
```

I think it reads the arrays as objects, perhaps it's better to throw an error.

@imbstack ^ is this intended behavior?

**Comment by djmitche** [comment]
I bet it doesn't do that in Python, so probably not expected..

**Comment by imbstack** [comment]
Indeed

```python
jsone.render({'$map': {'hello': 5, 'test': 9}, 'each(x)': ['${x.key}', {'$eval': 'x.val+1'}]}, {})
```

results in 

```
ValueError: dictionary update sequence element #0 has length 4; 2 is required
```

So yeah, this is a bug I expect.

**Comment by jonasfj** [comment]
probably we should make the python implementation throw a nicer error too :)

note, in the golang implementation I did an if-else and two different flows depending on whether I'm mapping an array or an object.. that made the code more readable too..

**Comment by Biboswan** [comment]
Hi,

As per code and docs **Given an array, map returns an array, and given an object, the result is an object**.
But here in the example $map is an object but each(x) is an array so how can the arrays be merged into a final object.

What shall be the correct output?

**Comment by djmitche** [comment]
I think it should be an error when `$map` is going to return an object but `each(x)` returns something that is not an object.

**Comment by Biboswan** [comment]
We can throw an error or is it better to return something like [[hello,6],[test,10]] in such case.We are getting this array result normally then since $map is an object it tries to make that array into an object.

**Comment by djmitche** [comment]
It's better to throw an error.

In general, languages should "error out" on bad inputs rather than do something clever.  If there is ever a consensus on what the language should do in that situation, it's easy to turn an error into some defined behavior.  It's *not* easy to change one clever behavior into another, as that breaks compatibility.

**Comment by Biboswan** [comment]
Alright,as you say.

**Comment by jonasfj** [comment]
> or is it better to return something like [[hello,6],[test,10]] in such case

I agree with dustin, it's better to throw an error... If in some future we want to invent a smarter logic we can do so later...
