### ISSUE TITLE
Escape sequences for strings in expressions

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#21]
Let's say I have an expression: `{$eval: " 'ab' "}` with more spacing.

What kind of escape sequences should we support.

Given that json-e is usually written as JSON or YAML.
We might not need a lot of escape sequences, example: `{"$eval": " 'a\nb' "}`, should already work, because when you parse it as JSON/YAML `\n` gets interpreted... 

So in order to make a string that contains ", I would have to write (as text):
`{"$eval": " \"a\\\"b\" "}`

Which also currently works, because `\"` is intepreted at json-e level... But all other escape sequences don't work at json-e level... Should we add those, or not?

Perhaps we don't want more escape sequences because you don't need them... when they are handled at JSON/YAML level... Perhaps we don't want any escape sequences, even for `\\\"` since it's kind of easy to get that wrong.

Thought everybody?

**Comment by djmitche** [comment]
Let's reserve all `\<char>` sequences, making everything but `\"` an error for now, since it seems to be the only absolutely required escape.  That is a simple choice now, with room to expand.

**Comment by hammad13060** [comment]
@jonasfj Just to clarify, we are trying to achieve strings with escape sequences in our expression language ?

I think ```{"$eval": " \"a\\\"b\" "}``` will raise unexpected end of input error right now. Can you elaborate on this a bit more :)

**Comment by jonasfj** [comment]
The text `{"$eval": " \"a\\\"b\" "}` must be escaped for entry in JS, then parsing returns:

> JSON.parse('{"$eval": " \\"a\\\\\\"b\\" "}') -> { '$eval': ' "a\\"b" ' }

Notice that `\\` in  a node.js string is actually the codepoint `\`

**Comment by TheNavigat** [comment]
I don't understand why do we need to consider escape sequences.

Entered string data should be escaped.  I don't understand what do we need to escape. 

If you're saying that entered data will be parsed as they're read by json-e, and we simply need to "unparse" it to be able to output the data, why don't we use something like html_special_chars in PHP? Why do we need to consider different escape sequences?

**Comment by jonasfj** [comment]
We parse the expression given in `{"$eval": "expr"}` after JSON parsing is done... So yes, we don't really need it...

**Comment by djmitche** [comment]
ok! :)
