### ISSUE TITLE
$eval shouldn't render it's argument before evaluation

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#211]
```yml
$eval: '5+${3+1}'
```
becomes `9`

This is IMO wrong, it should be an error...

Similarly, we should permit:
```yml
$eval: {$eval: '4+5'}
```

This double rendering is unnecessary and allows for meta-programming, as we'll effectively be evaluating generated code when we run the interpreter on the result of the first render..

I also note that this prevents static analysis were we extract which global variables are referenced in all expressions, as expressions can be generated. I'm going to propose a similar change for `$let`, as we shouldn't have dynamic variables in the top-level scope. Notice that there is no global object (by default).

---
I recognize that this requires changes to the spec... but I argue that:
 1) This is not a thing we should have added,
 2) it's probably not used anywhere, so let's get rid of it...
 3) usage is largely an anti-pattern

**Comment by djmitche** [comment]
I think you're right, let's get rid of it.
