### ISSUE TITLE
$let shouldn't render it's value, only the values of keys assigned (no dynamic variables)

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#212]
Example:
```yml
$let:
  ${'na' + 'me'}: jonasfj
in: 'hello ${name}'
```
Renders to `'hello jonasfj'`.

I propose that we forbid the `${'na' + 'me'}` part... 

Instead we require that in `{$let: X, in: T}`, `T` is a template as is now, while we require that `X` is an object mapping from `^[a-zA-Z_][a-zA-Z0-9_]*$` to templates, and that we render these templates.

This prevents crazy things like what I did above... It also ensures that static analysis can be used to determine which global variables are accessed. A feature that is useful in certain scenarios.

----
Note: I recognize that this will require a specification change, but that:
 1) it's unlikely that anyone is using this feature yet
 2) usage of this pattern is likely an anti-pattern... as there is no way to access top-levels variables if and only if they've been declared

**Comment by djmitche** [comment]
Agree :)

**Comment by jonasfj** [comment]
This was fixed in #214
