### ISSUE TITLE
Demo site doesn't render on mobile safari

### ISSUE THREAD

**Issue by imbstack** [taskcluster/json-e#218]
The following error is in the console:

```
SyntaxError: Invalid character '\u2160'
```

and the page is blank. I'm assuming this is some sort of weird webpack thing for now and will investigate a bit more. @eliperelman have you ever seen this before?

**Comment by Biboswan** [comment]
Hi,
Well it doesn't render on desktop safari as well.But strangely it renders on running locally with some display issues.Interface section is displayed incomplete...

**Comment by imbstack** [comment]
If it works locally but not on the production site, I expect it is some sort of webpack minification issue.

**Comment by eliperelman** [comment]
Could be a Babel minification bug. You can try turning off the mangling option to see if it resolves.
