### ISSUE TITLE
make sure $json sorts unicode strings the same across json-e implementations

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/json-e#222]
Per https://github.com/taskcluster/json-e/pull/221#issuecomment-355865572 :

> I think we should have tests that unicode keys are also sorted correctly. But I'm 100% okay, deferring that to another bug. Just file an issue, and we can fix it later -- there is potentially a lot of particularities to work out.

**Comment by escapewindow** [comment]
Per https://github.com/taskcluster/json-e/pull/221#pullrequestreview-87227483 : 

>  I think we should take "reasonable" measures to make $json output equivalent, but where that's impossible I'm also OK with a caveat in the docs that $json may introduce non-equivalent results. That's already the case for floating-point arithmetic, I believe.

**Comment by djmitche** [comment]
BTW, I said "reasonable" just to exclude heroic things like writing our own JSON encoder or some-such.  I think we can get somewhere between 99% and 100% fidelity between languages with no heroism.

**Comment by djmitche** [comment]
The task here is to check that unicode characters of all sorts (astral plane, etc.), when used as property names and passed to `{$json: ..}`, produce the same output.

**Comment by Biboswan** [comment]
For the following test templates we get same result in both javascript and python implementations.

template: {$json: {'\u3347\u0050': 1, '\uE1FF\u0010': 2, '\u0055\u0045': 3}}
template: {$json: {'u005A\u10000\u0050': 1, '\u{E1FFF}\u0010': 2, '\u0055a\u0045': 3}}
template: {$json: {'e\u{E3FFE}\u732b':'hey', '\u0041\u0012\u107000':'hi', 'A\u{24000}':'hello'}}
template: {$json: {'e\u{E3FFE}\u732b':'hey', '\u0041\u{24000}\u107000':'hi', 'A\u4FFF':'hello'}}
Any  more suggestions?

But they don't seem to  be sorted especially when code belongs to astral planes.
However when I used console.log to display the result it displays in expected sorted order.

**Comment by djmitche** [comment]
What is the expected sort order?  I'm not familiar with Unicode sorting, honestly.  And, if we're pretty confident that the languages all produce the same output, I'm not too concerned with whether that's sorted or not.

**Comment by djmitche** [comment]
I don't think the console sorts its results:
```
x
Object { x: 1, a: 2, aa: 3 }
```
so that's probably not the best thing to compare to.

Also, that test result looks like it's comparing strings with `\` and `u` and `{` characters in it, rather than one with unicode characters in it.

**Comment by Biboswan** [comment]
I meant this
````
console.log(jsone(template,{})
````
Yeah but if { is also compared its unicode is 007B but it comes after 007C  below.

````
template: {$json: {'\u{24000}\u732b':'hey', '\u007C\u{24000}\u107000':'hi', '\u0012\u{FFFF4}':'hello'}}

test result:
          
{"\\\\u0012\\\\u{FFFF4}":"hello","\\\\u007C\\\\u{24000}\\\\u107000":"hi","\\\\u{24000}\\\\u732b":"hey"}'`
```
Whatever may be the thing but since test case results are same in both js and python .I guess its ok.

**Comment by djmitche** [comment]
I don't think `\u` is a YAML escape code, so the strings you are comparing are `['\\', 'u', '0', '0', '1', '2', ..].join('')`, rather than actual unicode characters.

In YAML, I think we need to use double-quoted strings to get unicode escapes -- and no `{..}`.  Here's an example:

```yaml
$json:
  "\u2603": 'snowman'
  "\u007C": 'vertical line'
  "\u017d": 'Z-caron'
  "\U0001F602": 'joy'
  "\U0001F605": 'cold sweat'
```

And at least the JS implementation in [the playground](https://taskcluster.github.io/json-e/#Playground/%7B%7D&%24json%3A%0A%20%20%22%5Cu2603%22%3A%20'snowman'%0A%20%20%22%5Cu007C%22%3A%20'vertical%20line'%0A%20%20%22%5Cu017d%22%3A%20'Z-caron'%0A%20%20%22%5CU0001F602%22%3A%20'joy'%0A%20%20%22%5CU0001F605%22%3A%20'cold%20sweat'%0A) seems to sort those in order by codepoint.

**Comment by Biboswan** [comment]
Yeah after correcting YAML ,both gave proper and same results.I guess go implementation also needs to be checked.
Using go v1.9.2.getting go install: no install location for .go files listed on command line (GOBIN not set)
Not getting why.

**Comment by djmitche** [comment]
To build a Go project, you have to have the project in a deeply nested directory structure called a GOPATH.  Try the [hello world](https://golang.org/doc/install#testing) to compare.  I have my copy of json-e at ~/go/src/github.com/taskcluster/json-e with my GOPATH=/home/dustin/go.

**Comment by Biboswan** [comment]
Even golang produces same result.
However test cases fail in every implementation since result returned is in slightly different unicode representations corresponding to the language.

**Comment by djmitche** [comment]
Hm, can you make a PR with the test cases so I can see the errors?
