### ISSUE TITLE
json-e drops key/value pairs where the value is empty

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/json-e#223]
To get around this in cotv2 verification, I have to run my rebuilt definition and runtime definition through this function:

```python
def remove_empty_keys(values, remove=({}, None, [], 'null')):
    """Recursively remove key/value pairs where the value is in ``remove``.

    This is targeted at comparing json-e rebuilt task definitions, since
    json-e drops key/value pairs with empty values.

    Args:
        values (dict/list): the dict or list to remove empty keys from.

    Returns:
        values (dict/list): a dict or list copy, with empty keys removed.
    """
    if isinstance(values, dict):
        return {key: remove_empty_keys(value, remove=remove)
                for key, value in deepcopy(values).items() if value not in remove}
    if isinstance(values, list):
        return [remove_empty_keys(value, remove=remove)
                for value in deepcopy(values)]

    return values
```

Ideally, we would keep the key/value pair with the appropriate empty value, or have an option to do so.

**Comment by djmitche** [comment]
Can you give an example of this behavior?

```python
>>> import jsone
>>> jsone.render({"a": {"$eval": "a"}, "b": {"$eval": "b"}, "c": {"$eval": "c"}}, {"a": 0, "b": [], "c": {}})
{'a': 0, 'c': {}, 'b': []}
```

and I see a similar thing from JS in the [playground](https://taskcluster.github.io/json-e/#Playground)

Even if it did this, it would only be problematic if the languages behaved differently, right?

**Comment by escapewindow** [comment]
Sure.

```python
#!/usr/bin/env python
import jsone
import yaml
import json

with open("/src/gecko/mozilla-unified/.taskcluster.yml") as fh:
    tmpl = yaml.safe_load(fh)

print(tmpl)

task_ids = {
    'default': 'L-d1CNGUQGuOs_-wckujtw',
    'decision': 'L-d1CNGUQGuOs_-wckujtw',
}

context = {
 'as_slugid': lambda x: task_ids.get(x, task_ids['default']),
 'now': '2018-01-10T17:52:19.458Z',
 'push': {'comment': ' ',
          'owner': 'asasaki@mozilla.com',
          'pushdate': 1515606710,
          'pushlog_id': '245453',
          'revision': '0e6c499563239502fd76cabd9da1449aa3fd9f66'},
 'repository': {'level': '1',
                'project': 'try',
                'url': 'https://hg.mozilla.org/try'},
 'taskId': None,
 'tasks_for': 'hg-push',
}

print(json.dumps(jsone.render(
    tmpl, context
), sort_keys=True, indent=2))
```

If you compare the output to https://queue.taskcluster.net/v1/task/L-d1CNGUQGuOs_-wckujtw , it' snot the same. It's problematic because I can't deterministically rebuild the task definition for cot v2 verification without removing empty key/value pairs. It's possible the code is adding key/value pairs after `jsone.render`, in which case this is an issue for the taskgraph generation.

**Comment by escapewindow** [comment]
(I can try to get a smaller STR later)

**Comment by escapewindow** [comment]
Hm, I think I'm reading this wrong. I think json-e does create `extra.action.context.taskId` of `None`, and `payload.env.ACTION_TASK_ID` of `"null"`. Somewhere in between task definition generation and retrieving it from the queue, those key/value pairs disappear. I haven't figured out where, yet, but it's likely this issue doesn't belong in this repo.

**Comment by djmitche** [comment]
Hm, sorry, I'm still not seeing the repro -- one of those (from the Python) is a decision task, and one (L-d1CNGUQGuOs_-wckujtw) is an action task.  So they are quite different.  But I see e.g., `dependencies: []` in both..

However, I have a guess! Task definitions are broken up into fields like dependencies, payload, taskGroupId, .. in the queue service.  Most of them have default values, which the queue will fill in if not specified.  So I think this isn't a JSON-e issue, has to do with how we generate task definitions.

I can see two fixes: either specify values for all fields in all cases in `.taskcluster.yml`, or configure CoT to apply the same defaults that the queue does for all fields in a task definition (these defaults are in the JSON schema, so it's even possible to do so automatically).  Probably the first solution is the better one, although it will be a little brittle in that validation will fail when a new property is added to tasks.  But that hasn't happened for a year or two and I don't think we have plans to do so again at the moment.

**Comment by djmitche** [comment]
Ah just saw your update -- those sub-properties are definitely *not* defaulted in the queue -- it treats task.extra and task.payload as plain JSON blobs, and `null` is a valid JSON value so nothing should be deleting it.  So, yeah, a smaller STR might be good.

**Comment by escapewindow** [comment]
RIght now I'm guessing this is getting optimized out in the taskgraph code, but still just a guess. I'll try to narrow that down.

**Comment by djmitche** [comment]
Since it looks like this is not a JSON-e issue, I'm going to close this.  Easy to re-open if it does turn out to be a JSON-e issue.
