### ISSUE TITLE
write our own method (function)

### ISSUE THREAD

**Issue by shaikshakeel** [taskcluster/json-e#234]
Thanks for giving such a good library. 

How can we implement our own methods in this library ? 
in documentation you mentioned we can write `len()` function like below template 
```
template: {$eval: 'len([1, 2, 3])'}
context: {}
result: 3
```
is there any possibility to write our custom functions like 
```
template: {$eval: 'sum([1, 2, 3])'}
context: {}
result: 10
```
Thanks in advance

**Comment by djmitche** [comment]
Yes, such methods would need to be implemented in the native language (JS, Python, or Go) and supplied as a part of the context passed to the render method.

**Comment by shaikshakeel** [comment]
thanks @djmitche 

But i don't want to write those methods in context part, i have to provide a some custom methods, so that they can directly call in context part.

**Comment by djmitche** [comment]
I can't quite parse what that sentence means, but the only option for introducing custom functions is to include them in the context.  JSON-e is not a general-purpose programming language.  Introducing function definitions would allow loops and violate the constraint that all JSON-e renders complete in finite time.
