### ISSUE TITLE
Get index in map

### ISSUE THREAD

**Issue by shaikshakeel** [taskcluster/json-e#235]
in map function 

we can apply our custom transformation to each value of map(either array element or JSON key, value)

is there any possibility  to get index of element in case arrays ?
```
template:
  $map: [2, 4, 6]
  each(x,index): {$eval: 'x + index'}
context:  {a: 1}
result:   [2, 5, 8]

```

**Comment by djmitche** [comment]
This sound OK to me.  Do you want to implement it?

**Comment by shaikshakeel** [comment]
Mostly, trying to understand how map works in json-e :)
