### ISSUE TITLE
Truithness of operators

### ISSUE THREAD

**Issue by shaikshakeel** [taskcluster/json-e#237]
In documentation you mentioned that null will be treated as false. 

I am trying this example in python

Here example : 
```
context : 
{
    "data" : {
    "started_at" : null,
    "resolved_at" : null
    }
}
```

template : 
```
{
    "a" : {
        "$if" : "'data.started_at'== null ", "then" : "a", "else" : "b"
    }
}
```

i am expecting output as : 
```
{
   "a" : "a"
}

```
but i am getting output as : 
```
{
    "a" : "b"
}
```

**Comment by djmitche** [comment]
Thanks for the reproduction!  In this case, you're not using `null` as a boolean -- rather, you're comparing a string (`data.started_at`) with `null`.  Those aren't equal, so JSON-e takes the "else" branch.

Drop the single quotes and you should see what you expect.
