### ISSUE TITLE
CLI tool for JSON-e

### ISSUE THREAD

**Issue by wryun** [taskcluster/json-e#238]
Just wrote:

https://github.com/wryun/rjsone

Is it worth PR-ing (with some tests, perhaps...)? Or maybe you could link to it on the website?

**Comment by djmitche** [comment]
That's really cool!

I think it makes sense as a separate project more than one incorporated in this repo.  But I'd love to have a link to it in the docs in this repo.  Do you want to make a PR to add that?

**Comment by wryun** [comment]
Thanks!
