### ISSUE TITLE
provide a "map" API entry point

### ISSUE THREAD

**Issue by mhalle** [taskcluster/json-e#243]
The current API applies a template to a single context.  A standard API entry point that took a template and an array/iterator of contexts, returning an array/iterator of results, would save the cost of repeated template parsing.  This operation is equivalent to a "map" operator.

Such a method would allow, say, the rows of a table to transformed all at once using a row template.

One could always write a template that dealt with an array of values. But flat arrays are such a common data structure that providing a dedicated method seems worthwhile.  Moving iteration out of the template also simplifies the template.

**Comment by djmitche** [comment]
I'm not sure this would be faster than just calling `jsone.render(templates[i], context)` in a loop.  JSON-e doesn't do any parsing (that's your job, if your input is in JSON or YAML or XML or whatever), so there's no savings on that point.

Have I misunderstood the idea?

**Comment by mhalle** [comment]
This would be a replacement for 

`jsone.render(template, context[i]);`

`const renderedArray = jsone.rendermany(template, contextArray);`

**Comment by djmitche** [comment]
What's the advantage over `contextArray.map(context => jsone.render(template, context))`?

**Comment by mhalle** [comment]
What's the overhead of parsing/interpreting the template per context?  You'll save that per invocation.

**Comment by djmitche** [comment]
There's no parsing -- that's your responsibility before you call render.
The render is a single pass over the data structure, so while there's
probably room for optimization in the details, there's no fast win to be
had by skipping a pass over the template.
