### ISSUE TITLE
Throw a useful error for `$then`

### ISSUE THREAD

**Issue by jgraham** [taskcluster/json-e#252]
At present writing
```
$if: foo
$then:
  bar
$else:
  baz
```

generates something of type `null`, when it should probably be a syntax error informing the user that `$then:` should be spelled `then:` (no `$`).

**Comment by osumgbachiamaka** [comment]
@owlishDeveloper when i run the python test in the virtual env i created it passes, but when i run it outside it keeps returning this error - 
pkg_resources.VersionConflict: (attrs 18.2.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('attrs>=19.2.0'))

**Comment by owlishDeveloper** [comment]
@osumgbachiamaka please do not work on this issue without asking and having it assigned to you first. If you'd like to apply for the JSON-e project, the first task is to setup your development environment and send me the screenshots of your successful test runs for all three implementations. Thank you!

**Comment by owlishDeveloper** [comment]
@osumgbachiamaka Received your screenshots, thank you! Assigning this issue to you.

**Comment by owlishDeveloper** [comment]
Fixed!
