### ISSUE TITLE
ESLint configuration not detecting unused variables

### ISSUE THREAD

**Issue by edmorley** [taskcluster/json-e#267]
It appears that the current ESLint configuration doesn't pick up the following unused variable (or alternatively isn't being run in CI; I haven't looked closely):
https://github.com/taskcluster/json-e/blob/24a97f3474bc4e9625b17d3b6e91f9ff99eef380/src/index.js#L3

It might be worth switching to eg `airbnb-base`, to ensure maximal coverage. (This can optionally be combined with the ESLint Prettier configuration; see the Treeherder repo for an example)

**Comment by imbstack** [comment]
We've switched to just using the `eslint:recommended` set of rules and should catch these now!
