### ISSUE TITLE
gh-pages url is blank

### ISSUE THREAD

**Issue by srfraser** [taskcluster/json-e#281]
https://taskcluster.github.io/json-e/ has an empty page as content, and the history appears to show it's been there for some time. Should the links in the project description and README be pointing elsewhere?

The docs appear to be at https://docs.taskcluster.net/docs/reference/libraries/json-e - is that authoritative source of them?

**Comment by djmitche** [comment]
No, that should be working, and was until recently.

**Comment by djmitche** [comment]
Looks like it's back, after reverting 4a9e39d0b708abb841d899d904fda4a90bba750e.  So I guess rebass isn't following semver!
