### ISSUE TITLE
Error message: differentiate path/variable from the rest of the message

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/json-e#283]
**Reproduce:**
Template:
```
a: ${event.after}
```
Context:
```
{
  "event": {}
}
```

In the python implementation, I'm getting the error:
> jsone.shared.TemplateError: TemplateError at template.a: after not found in

This threw me off, since I didn't initially realize that "after" was the specific property that was missing. I assumed that the error message was describing that the issue happened "after" a property wasn't found.
Perhaps the variable could be quoted? Perhaps something like:

> jsone.shared.TemplateError: TemplateError at template.a: "after" not found in

:thinking:

**Comment by djmitche** [comment]
I like it.

**Comment by ruchikabgosain** [comment]
Hello @mitchhentges is this issue available?

**Comment by mitchhentges** [comment]
@ruchikabgosain hey! I'm not working on this issue, I think you're all clear :smile:

**Comment by echessa** [comment]
Hi @owlishDeveloper can I work on this.

**Comment by djmitche** [comment]
@echessa this issue is for the [JSON-e-related Outreachy project](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/implement-short-circuit-evaluation/cfp/) which has its own required first steps described in that page.  You're welcome to apply to that project as well!

**Comment by owlishDeveloper** [comment]
Hi @echessa Dustin is correct. These issues here are reserved for the applicants for that project. You are more than welcome to apply for it! To apply, you need to set up your development environment, run the tests and send me the screenshots of the successful test run. I will then assign the issue to you.

**Comment by echessa** [comment]
@owlishDeveloper I already sent the screenshots.

**Comment by owlishDeveloper** [comment]
Thank you @echessa ! This issue is all yours!

**Comment by stuartelimu** [comment]
Can I work on this issue too ?

**Comment by echessa** [comment]
Hi @stuartelimu I'm currently working on it. There are other unassigned [good first issues](https://github.com/taskcluster/json-e/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by owlishDeveloper** [comment]
@stuartelimu this issue is already assigned. I assigned another issue to you. Please be patient! Thank you!

**Comment by stuartelimu** [comment]
thank you, am a bit new to this that's why i asked for multiple issues am
so sorry and thank you. i appreciate

**Comment by owlishDeveloper** [comment]
Fixed in #327
