### ISSUE TITLE
[python] Define python_requires in setup.py to show compatibility with both py2 and py3

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/json-e#287]
I've discovered that the `json-e` library doesn't support Python 3 - for example, when running `jsone.render(...)`, the strings in the task payloads had byte prefixes in the strings themselves, such as: `"b'A1k6Dd-jRr-KQnccuFjc2A'"`.

Perhaps we can use the [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) property in `setup.py` to document that the `json-e` package is specific to Python 2?

**Comment by djmitche** [comment]
I *does* support Python 3, so this is a bug :)

It sounds like the bug is actually in whatever is providing slugids?  I seem to recall a patch to slugid-py to generate slugids as strings (rather than bytes), but I can't find it now.

**Comment by mitchhentges** [comment]
Aha, right, this caused by the [`slugid`](https://pypi.org/project/slugid/) library, not `json-e`!
I thought that `slugid` was an `install_requires` of `json-e`, but it looks like I'm mistaken.

-----

It might still be worth defining `python_requires` in `setup.py`, I'll do a PR :smile:
