### ISSUE TITLE
Consider replacing json-stable-stringify dependency for OSS licensing reasons

### ISSUE THREAD

**Issue by ezzatron** [taskcluster/json-e#299]
The [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) library you currently depend on does not have a license. There are many alternatives depending on your needs, but perhaps the most popular is [json-stable-stringify-without-jsonify](https://www.npmjs.com/package/json-stable-stringify-without-jsonify).

There are performance-oriented alternatives too, such as [fastest-stable-stringify](https://www.npmjs.com/package/fastest-stable-stringify), but they usually drop support for the `space` option.

**Comment by djmitche** [comment]
Ah, thanks for finding that!
