### ISSUE TITLE
JSON-E template Media/MIME type?

### ISSUE THREAD

**Issue by bollwyvl** [taskcluster/json-e#319]
Thanks for JSON-e!

Has anyone started a convention around a media type for JSON-e templates? I've been tinkering with some [JSON-e for jupyter](https://github.com/deathbeds/wxyz/pull/14) where we use them rather a lot for the hand-off between client and server, rendering, registering syntax modes, etc.

I guess the end-state would be an [IANA registration](https://www.iana.org/assignments/media-types/media-types.xhtml), but in the near-term, just something "semi-official" here I can point to would be "enough".

Absent any other proposal, and maybe a little verbose, but probably most accurate at this point might be something like:
```
application/vnd.taskcluster.json-e.v3+json
```
with a "some day" of 
```
application/e+json
``` 
(though i guess the format would need a `$version` to not need an explicit version)

**Comment by djmitche** [comment]
Thanks for using json-e!

I've never participated in a media type registration before, so it's hard to know even if it's appropriate here.  Do you have an example of a similar media type and its registration process?

**Comment by bollwyvl** [comment]
Thanks for writing and open sourcing it!

I've never done a "real" mime type either! But the vnd namespace is meant
just for such ad hoc things. We've made/adopted a few:

https://jupyter.readthedocs.io/en/latest/reference/mimetype.html

A file pre-suffix family might also be reasonable, e.g. .e.json, .e.yml,
e.yaml

Really just having a note in the docs would be sufficient: if it's
documented, it's real enough for me! Happy to open a PR!

**Comment by djmitche** [comment]
Per https://tools.ietf.org/html/rfc6838#section-5.1, it looks like we should run it by `media-types@iana.org mailing` first.  I'm happy to do that, but I'd like to understand what I'm asking for first.  So, I'm curious why you added `.v3` in there, and I'm not sure what you meant by `$version`.  Can you explain more?

**Comment by bollwyvl** [comment]
If the list of $keywords grows (or especially shrinks!) or the meaning of a
$kw changes, an implementation wouldn't know how to handle it until it
failed to process. Putting v3 in the type name or a required $version in
the root of (a future version of) the spec would make it unambiguous.

Alternately, specifying a (versioned) $schema would do the trick, but I
haven't fully groked whether that's even possible! Sure would be nice for
schema-aware editing, though!

>

**Comment by djmitche** [comment]
I sent a message to the IETF list.  Sorry for the delay!

**Comment by djmitche** [comment]
Archive: https://mailarchive.ietf.org/arch/browse/media-types/?qdr=d

(message is still awaiting moderation)

**Comment by bollwyvl** [comment]
Exciting stuff!

**Comment by djmitche** [comment]
It looks like, despite what the RFC says, we must register this, which requires filling out the template:

https://tools.ietf.org/html/rfc6838#section-5.6

Can you paste that here and I will forward it to the list?  I'm happy to be "Change Controller".

**Comment by djmitche** [comment]
(I'm also happy for you to follow up directly to the list -- I don't have much time to work on this but I support it happening)
