### ISSUE TITLE
`expects.sort is not a function`

### ISSUE THREAD

**Issue by mozbhearsum** [taskcluster/json-e#320]
I got the above error with this template and context (edited to use minimal STR):
```
$let:
  foo: ${bar[2:}
```

context:
```
{
bar: "refs/heads/testing",
}
```

Also reproducible on https://taskcluster.github.io/json-e/#Playground, although it shows up as `t.sort is not a function`.

The issues turned out to be a missing `]`, but the error didn't make it easy to discover that.

**Comment by djmitche** [comment]
@mozbhearsum can you boil that repro down a little?  If so, fixing this might make a good contributor bug (in general, error handling is pretty weak).

**Comment by owlishDeveloper** [comment]
Fixed in #333
