### ISSUE TITLE
Functions call does not work in v4.x

### ISSUE THREAD

**Issue by the-question** [taskcluster/json-e#354]
Reproduction in Playground:  
https://json-e.js.org/#Playground/%7B%7D&%7B%24eval%3A%20'max(3%2C%202)'%7D

**Comment by djmitche** [comment]
```yarn
template: {$eval: 'max(3, 2)'}
context: {}
```

**Comment by the-question** [comment]
The problem seems to come from https://github.com/taskcluster/json-e/blob/master/src/interpreter.js#L12 where `e.constructor.name` returns an empty string

**Comment by djmitche** [comment]
I see this working on master, actually (see test case PR).  It appears it's not working in the playground perhaps because the playground is running a different version?  Do you see this on a checkout of v4.0.1 or master?

**Comment by the-question** [comment]
I have this problem on v4.0.1, I did not test it against master

**Comment by djmitche** [comment]
Hm, I've been unable to reproduce.  Can you show a code snippet that reproduces?

**Comment by the-question** [comment]
On the website's Playground, I get an error in the result with:
```
template: {$eval: 'max(3, 2)'}
context: {}
```

I don't have the error in NodeJS. It also seems I don't have the error when webpack builds it in dev mode. But I do have the error when webpack build in production mode.
I made a really dirty CodeSandbox: https://codesandbox.io/s/goofy-shape-pi3q0
To reproduce, you can:
- export the ZIP
- `npm install`
- `npm run build` to build using webpack in production mode
- open the resulting `build/index.html` in the browser. In the console, you will see the error: `TypeError: this[("visit_" + e.constructor.name)] is not a function`

My apologies for the dirty reproduce, I tried to make something ASAP.
Thanks a lot for your time and your reactivity!

**Comment by the-question** [comment]
@djmitche I found out that Webpack get's rid of constructor's name in production mode. I created #356  to replace usage of `constructor.name` with a manually set property `constructorName`. It's slightly less elegant than using the constructor's name but at least it works consistently. Could you review this PR please?

**Comment by the-question** [comment]
@djmitche Anything I could do to help move this forward? This is currently a blocker for me to upgrade to 4.x
