### ISSUE TITLE
Run as sh commands in jenkinsfile

### ISSUE THREAD

**Issue by liaogz82** [taskcluster/json-e#360]
Hi. is there a way to run this as an sh command in Jenkinsfile?

**Comment by djmitche** [comment]
You would need to build an executable in your language of choice, but that should be fairly simple.  For example, you might write a Go program that parses its args as JSON files, with the first being the template and the second being the context.  Or you might write a Python script that parses its arg as YAML and reads the template on stdin, etc.  In any case it shouldn't be more than a few dozen lines of code.
