### ISSUE TITLE
Demo website for json-e

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#38]
We should make a github pages site that looks this:

![https://img42.com/0b78N](https://cdn.img42.com/74ea5a4dc0e90396733473cc23fa14a3.png)

With a live "try it" editor... that way we can easily test bugs etc...

**Comment by hammad13060** [comment]
Seems like a good Idea. I don't have much idea about front end development, so can you give some pointers on how to start ? Do we have some ```jekyll``` templates which server our purpose ?

**Comment by jonasfj** [comment]
I figure we can built it with neutrino or something... So we get everything
bundled into a single js file...

We'll probably have to do it a subfolder...As it'll need it's own
package.json... Hmm maybe not sure how we structure it.. maybe devDeps will
do...

Ping me on IRC... Eli is sure to have some ideas for how we can quickly
hack this together... IMO we want it to be super easy to update, so we keep
it up to date...

Den 22. feb. 2017 7.49 PM skrev "Hammad Akhtar" <notifications@github.com>:

**Comment by jonasfj** [comment]
@hammad13060 Hi, sorry I missed on you on IRC.
Thinking about we can probably just use http://browserify.org/ to compile all the files into a single bundle that we can load into an HTML... then we don't need anything complicated.

You add `browserify` and `codemirror`, `jquery`, etc... as `devDependencies` in `package.json`. 
Then create files `demo.js` and `index.html`, in `demo.js` we just write a script that compile with browserify bundles up everything and then we include that `index.html`. We can use `npm run build-demo` to build browserify thing, we'll just add a script command in `package.json`.

**Comment by hammad13060** [comment]
Hmm..this looks good :)

Just few clarifications
1. first we will build josn-e using ```npm run compile```
2. then we will include ```lib/index.js``` to out ```demo.js```
3. then we will run ```npm run build-demo```
4. now we are good to go
am I right ?

What directory structure should we follow for website ?

**Comment by hammad13060** [comment]
Hi @jonasfj I ran into following issue 

I did following steps
1. ```npm install browserify -g```
2. ```npm install codemirror --save-dev```

Now my ```demo.js``` looks like this

```javascript
let CodeMirror = require('codemirror');
let editor = CodeMirror(document.getElementById("try-it-template"), {
  value: 'let a = 123\n',
  mode: 'javascript',
});
```
Finally I transpile ```demo.js``` to ```budnle.js``` using ```browserify demo.js -o bundle.js```

**Note:** I have an index.html containing ```div``` element with id ```try-it-template```.

But editor is not rendered properly :(
I think I need to somehow require ```mode``` in my ```demo.js``` which is ```javascript``` in this case. So can you suggest how to go about this :)

**Comment by jonasfj** [comment]
You can make `browserify` a devdep too... command specified in `scripts` section of `package.json` runs with `./node_module/.bin/` in `PATH`.

yeah, you'll likely also need to include some stylesheets... I guess we could have a command that copies the relevant stylesheets from `./node_modules/codemirror/...` into the `demo/` folder or something.

**Comment by jonasfj** [comment]
Note. `let jsone = require('./lib')` should also just work (TM) with browserify. As long as run `npm run compile` first.

**Comment by djmitche** [comment]
The remaining bit here is, I think, to include some examples in the view -- maybe it makes sense for this to be the documentation, with "live" examples?  We also need to link this from the README.

**Comment by jonasfj** [comment]
Ideally, we have an examples.yml file with same format as specification.yml... but with only the essential examples...

Then we can load said examples.yml from both demo site and tests... So it's not untested... Or we even better we have a hack that parsed out the examples from the readme for use in tests and interactive demo...

**Comment by TheNavigat** [comment]
@jonasfj Why not parse `specification.yml` directly?

**Comment by djmitche** [comment]
I'd prefer to parse them out of the README, or even render the README as markdown with live examples replacing the `yaml` sections.  The `specification.yml` file already has hundreds of examples and will have a lot more -- it's not a great way to learn.  It also lacks any narrative "flow" from one feature to the next - it would appear to the user as an un-ordered, barely described set of examples.

**Comment by jonasfj** [comment]
> Why not parse specification.yml directly?

it's a very long file with **many** entries... :)

**Comment by djmitche** [comment]
We have a site now that's decent, but there are some ideas above that would help to make the language more self-documenting.  We should also think about how the site gets built -- updating `docs/bundle.js` is getting to be a bit of a drag.  Still, neither is high priority.

**Comment by imbstack** [comment]
@djmitche while I was working on the other three issues for the demo site I ended up redoing most of it anyway. I'll assign this to myself. Hopefully you haven't done much work on this yet! It still needs a way to not force us to update the bundle ourselves manually, but that might require moving off of github pages.

**Comment by djmitche** [comment]
I hadn't touched this, and your work looks awesome :)

**Comment by djmitche** [comment]
@eliperelman could we get https://jsone.js somehow?

**Comment by eliperelman** [comment]
@djmitche .js isn't a valid TLD, but you can register with .js.org:

https://js.org/
