### ISSUE TITLE
`json-e.org` is down

### ISSUE THREAD

**Issue by noahlaux** [taskcluster/json-e#380]
Is seems like the js assets on `gh-pages` from the latest build are broken as the site doesn't work and there's a JS error in the console.

**Comment by djmitche** [comment]
`git blame` blames 4097892ef98c84efa66bfe6c4010781ed8bef898

**Comment by djmitche** [comment]
It looks like
```
# $sort the otherwise arbitrarily ordered results
```
confuses https://github.com/jonschlinkert/sections, which doesn't realize it's contained in a literal block.  That's pretty lame!  But that library appears totally unmaintained, so perhaps there's no sense in fixing it.  The `markdown` library can parse the README correctly, but it doesn't give any positions in the original text, so no way to extract the markdown text for each section.

**Comment by djmitche** [comment]
Should be back up and running shortly..

**Comment by djmitche** [comment]
(confirmed)
