### ISSUE TITLE
Making json-e asynchronous

### ISSUE THREAD

**Issue by hammad13060** [taskcluster/json-e#39]
@jonasfj 
Inspired by the fact we may define some functions in context which may do some async work like file I/O, DB access etc.

**Comment by djmitche** [comment]
I think we should explicitly disallow this sort of thing -- having filesystem or network access from JSON-E sounds dangerous to me!

**Comment by djmitche** [comment]
i agree with myself -- JSON-e should not be doing anything that might require FS access.
