### ISSUE TITLE
Reference the complete context of a scalar type

### ISSUE THREAD

**Issue by git-developer** [taskcluster/json-e#408]
I have a use case where the context is not provided as a JSON object or array, but as a number.
I'd like to transform the number using an `$eval` statement, e.g.:

* Context: `-12.34`
* Template: `$eval: '0 - ${.}'`
* Result: `12.34`

I didn't find a syntax to reference the complete context. Is there a way to to that?

**Comment by djmitche** [comment]
The intent is that the context always be an object.  In cases where only one value is required, that would be wrapped, e.g., `{"number": -12.34}`.  The reason for this is that the context is a set of variables, and therefore must have a key/value form.  I suspect that the JS implementation allows a non-object context, and maybe a few others.  I know the Rust implementation does not, though.

So, I think that's the fix in your case.  However, I'll keep this issue open to check that all implementations correctly reject a non-object context.

**Comment by git-developer** [comment]
Thanks for your fast response.

Unfortunately, your suggestion does not apply to my use case where the context is provided via MQTT and directly handed over as context to json-e. But since you clearly say that an object is expected by json-e, I guess I have to look for an alternative solution.

This issue may be closed when the context is required to be an object.

**Comment by djmitche** [comment]
Could the thing wrapping the MQTT create a context with `{"payload": <thing from mqtt>}`?

**Comment by git-developer** [comment]
I've been looking for a simple MQTT-to-MQTT adapter and found [mqtt-transformer](https://github.com/tg44/mqtt-transformer) which delegates the transformation part to json-e. So for my use case of receiving a scalar value (number, string), either json-e or the mqtt-transformer would have to be extended. json-e was my first try, so now I'll head over to mqtt-transformer.
