### ISSUE TITLE
Need `exists` syntax in expression language

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#45]
We may want to conditionalize something on the presence of an object property, or on the presence of a property in the context.

Depending on how we handle missing object properties, the latter might be easy.  But for context properties, we will need a function.  Perhaps `exists(abc)` and `exists(abc.def)`, where both would fail if there is no `abc` in the context, and the latter would fail if `abc` is not an object or does not have a `def` property.

**Comment by djmitche** [comment]
Ah, I see we have `"foo" in bar` in the expression language, so that handles everything but the existence of an identifier in the context itself.

**Comment by jonasfj** [comment]
> that handles everything but the existence of an identifier in the context itself.

I propose that we don't handle that... If people really want an exists function they can add their own.

Or we can force the global context to have a self-reference `global`, how about that?

**Comment by djmitche** [comment]
I think it's probably fair to omit this - ideally the list of context top-level properties would be fixed, even if you're dealing with arbitrary data.  For example, tc-github would put the webhook body in `body` or something, not pass the whole thing as context.
