### ISSUE TITLE
Make `fromNow` a built-in function, instead of an operator

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#46]
Replace `{$fromNow: '1 second'}` with `{$eval: 'fromNow("1 second")'}`.

**Comment by jonasfj** [comment]
One could argue that this is so useful that we should have both?

Regardless I don't object to this change...

**Comment by TheNavigat** [comment]
I opted for allowing both. What are your thoughts, @djmitche ?

**Comment by djmitche** [comment]
I think that's OK.  We can document that `{$fromNow: x}` is shorthand for `{$eval: "fromNow(x)"}`.
