### ISSUE TITLE
Add `$let`

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#48]
It would be really convenient to write
```javascript
{$let: {
    ts: "fromNow('100 days')",
    foo: "bar + 10",
  },
 in: [{$eval: "parseDate(ts).year"}, {$eval: "parseDate(ts).month"}, {$eval: "parseDate(ts).day"}]}
```
This doesn't introduce any potential for looping or recursion, but it does make the context handling a little more complicated since within the `in` there are additional "variables" available that are not in the global context.

Note that the let variables are not ordered, so the cannot depend on one another (that is, `foo: "ts + 10"` would not work).

**Comment by TheNavigat** [comment]
I don't understand the example. Don't we have only one context? How is a list of `{eval: "..."}` supposed to work? What should be the result?

**Comment by djmitche** [comment]
Sorry, I didn't explain it very well.  The idea is: `{$let: <variables>, in: <template>}`.  When evaluated, the <template> would be rendered with a context consisting of the existing context plus any variables in <variables>.

For example, if we needed to construct a data structure with exactly the same timestamp in two places, we couldn't use `$fromNow` directly since it will be called at two slightly different times.  This construct might also be useful to drastically shorten templates, if they have some repetitive expression in them.

So yes, in this case we get away from "one context" into "the context in which this data structure is rendered", where sub-data-structures might be rendered with a different context.

This use of `let` is similar to functional programming languages such as scheme or ml.
