### ISSUE TITLE
Support escaping from string interpolation

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#66]
What if you wanted a literal "${" in a string?
```yaml
try-this: "a literal ${ in a string"
```

**Comment by TheNavigat** [comment]
Does a `$literal` operator sound like too much for such feature? It makes sense to me.

**Comment by djmitche** [comment]
I was thinking about just adding some string syntax, maybe `$$` -> `$`, so that `"$${"` would render as `"${"` and not do any interpolation.

A `$literal` operator isn't a bad idea, although I think if the user has a big chunk of data they want included literally, it would make more sense to put that in the context and include it with `{$eval: "chunk_of_data"}`.

**Comment by TheNavigat** [comment]
Are we talking about escaping the `$` symbol itself? If so, your approach sounds solid to me.

**Comment by djmitche** [comment]
Yes, I think that's the critical character.

**Comment by imbstack** [comment]
I believe this is resolved now if the specification file is doing what I think it is. Please reopen if I'm wrong!
