### ISSUE TITLE
Allow escaping operators

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#67]
How do I write a literal `{$eval: '2+2'}`?

**Comment by TheNavigat** [comment]
https://github.com/taskcluster/json-e/issues/66#issuecomment-305672108. What about a `$literal` operator?

**Comment by djmitche** [comment]
We could do a parallel thing here, and say any property name starting with `$$` will come out with prefix `$`:

```yaml
template: {$$eval: '2+2'}
result: {$eval: '2+2'}
```
