### ISSUE TITLE
Handle top-level deletion markers as an error

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#69]
Currently `{$if: 0, then: 1}` will render to `undefined`, which isn't JSON-able.  It should be an error.

**Comment by TheNavigat** [comment]
Why don't we return `{}` instead?

In some use cases, such as polling, I think it'd be best to return an empty object instead of an error. What are your thoughts?

**Comment by djmitche** [comment]
In the example here the caller is expecting an integer, not an object.  What do you think about returning `null` in this case?

**Comment by TheNavigat** [comment]
Yep, `null` should do. Should I change the line?

**Comment by djmitche** [comment]
yes, please :)

**Comment by TheNavigat** [comment]
Closed by https://github.com/taskcluster/json-e/pull/87
