### ISSUE TITLE
Compare things deeply

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#72]
That JS does weird undefined things when you use `==` on objects or arrays is a JS bug, and we shouldn't propagate that into JSON-e.  Instead, we should do deep object comparisons.

**Comment by TheNavigat** [comment]
(For future reference)

The `==` operator parsing is done here, https://github.com/taskcluster/json-e/blob/master/src/interpreter.js#L260. We should probably replace that with a function that does deep comparison.

**Comment by TheNavigat** [comment]
What do you think of this implementation? https://github.com/marijnh/Eloquent-JavaScript/blob/master/code/solutions/04_4_deep_comparison.js

**Comment by djmitche** [comment]
@jonasfj is that reasonable? I don't know what things like `assert.equal` use for deep equality..

**Comment by jonasfj** [comment]
https://lodash.com/docs/4.17.4#isEqual

We only allow JSON value right? so equality is based on `===` for non-object/arrays... We don't look at inherent properties for objects (as there should be none).
