### ISSUE TITLE
Define behavior for accessing undefined keys in an object

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#77]
Example: `{$eval: '({"test": 4}).foo'}`

Questions:
 * Does this eval to `null`
 * Does it throw an error
 * How do you get an object with default like `x.foo || 'default-value'` in js

As @djmitche said in comment:
> So I can see a few options:
> * `x['foo']` and `x.foo` are `null` - but this will not "go away" when users want it to
> * `x['foo']` and `x.foo` are a delete marker - this will require handling delete markers within the expression language, where currently they're only handled in array/object construction
> * `x['foo']` and `x.foo` are errors, but `get(x, 'foo', 123)` is `123`, and the `get` built-in always requires that third argument.
> Preferences?

I don't know how feasible it is... But I'm tempted to suggest an `or` operator... as in `x.foo or 'default-value'`. But having such an operator only allowed with a property access on the right hand side seems a bit crazy (and very context sensitive)...

I suggest that we tweak it such that `x.foo == null` and  `x.foo || 'default-value'` both works. This is supposed to be a simple expression language, being super explicit as is preferred in python might not be the best choice for an embedded expression language.

**Comment by djmitche** [comment]
Just to throw options on the fire:
 * `x['foo']` evaluates to null, but `x.foo` is an error
 * `x['foo', 'default']` evaluates to `'default'`, while `x.foo` is always an error

**Comment by jonasfj** [comment]
I like the first one `x.foo` is an error and `x['foo']` is null...

Especially if we also tweak `||` to work with non-booleans which seems
sane...

Hmm, maybe it is a bit crazy to not just return null from both of them...
Whether a template produces an error or produces and unexpected result
doesn't matter too much in the use-cases we have... Since we will be
checking the result against a JSON schema... And we don't have a good
course of action in case of errors anyways.. just saying...

Den 24. maj 2017 7.28 AM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by djmitche** [comment]
Yeah, I think it's a matter of language preference -- JS seems all loosey-goosey to me, whereas Python probably seems really uptight to you :)

**Comment by djmitche** [comment]
So I agree, this option:
 * `x['foo']` evaluates to `null`, but `x.foo` is an error
